### ISSUE TITLE
Container stops very slowly

### ISSUE THREAD

**Issue by dandjo** [wodby/webgrind#6]
### Summary

The wodby/webgrind container takes 10 seconds (which is the maximum a container is allowed to stop) when issuing a SIGTERM (`Ctrl + C` after `docker compose up`). I guess the container is not properly handling signals. All my other container stop within a second.

### docker-compose.yml
```
  webgrind:
    image: wodby/webgrind:1.9-1.30.0
    container_name: tm_${PROJECT_NAME}_webgrind
    environment:
      WEBGRIND_ORIG_CODEBASE_PATH: /var/www
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.tm_${PROJECT_NAME}_webgrind.loadbalancer.server.port=8080'
      - 'traefik.http.routers.tm_${PROJECT_NAME}_webgrind.entrypoints=http'
      - 'traefik.http.routers.tm_${PROJECT_NAME}_webgrind.rule=Host(`webgrind.${DOMAIN_NAME}`)'
    volumes:
      - xdebug_data:/tmp
      - ./app:/mnt/codebase
```

### Demonstration
https://github.com/user-attachments/assets/2af4bfee-06fc-424d-97d4-dad389c16a11
